### ISSUE TITLE
Version 2.1.0

### ISSUE THREAD

**Issue by squadette** [squadette/hammer.js#2]
The forked package name is `@squadette/hammerjs`.

Version 2.1.0 is the original version 2.0.8 with the following fixes planned:

- [x] modernize build just enough to work in modern environment;
- [x]  fix Travis CI build;
- [x]  fix calculating rotation angle;
- [x]  fix running hammer.js in server-side rendering environment;
- [ ]  fix some known issues in documentation and examples;
- [ ]  fix issue with pan and pinch conflicting (workaround is to enable/disable pinch detector in runtime, but it's better to fix the root cause);
- [ ]  some other trivial fixes could be included.

To reach 2.1.0 we're going to release a series of `-pre` versions that must be tested as widely as possible and confirmed to work in your environments.

**Comment by The-Code-Monkey** [comment]
@squadette whats the plan with this are you still planning on updating as the last update was 2019

**Comment by squadette** [comment]
It would be really nice if people could test -pre releases in their production and confirm that they're happy with it.   It works in my production.

Also, if somebody could fix the issue with pan and pinch conflicting and submit a PR that would be awesome.

Also, if somebody knows any good patches available in other repositories that could be easily included in the release that would be great.

**Comment by squadette** [comment]
Btw here is a write-up of how gesture detection works: https://squadette.github.io/hammer.js/understanding-gestures/
